language: node_js
cache:
  directories:
    - node_modules
services:
  - docker
deploy:
  - echo $USERNAME
  - docker login --username=$USERNAME --password=$HEROKU_KEY registry.heroku.com
  - heroku container: push web building-up-client
