language: node_js
services:
  - docker
node_js:
    - "stable" 
  cache:
    directories:
    - node_modules

    deploy:
      provider: heroku
      api_key:
        secure: "86dc0c2c-a46f-444b-8a16-7eac55a137d1"